version: "3.7"
services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: database
      TZ: Europe/Berlin
    volumes:
      - "./mysql-startup:/docker-entrypoint-initdb.d"
